apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx   
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 350m
            memory: 64Mi