apiVersion: v1
kind: Pod
metadata:
  name: tolerations-container
spec:
  containers:
  - name: tolerations-container
    image: nginx
  # tolerations:
  # - key: "gpu"
  #   operator: "Equal"
  #   value: "nvidia"
  #   effect: "NoSchedule"