apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesdemo-deployment
  labels:
    app: kubernetesdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetesdemo
  template:
    metadata:
      labels:
        app: kubernetesdemo
    spec:
      containers:
      - name: kubernetesdemo
        image: wolfgangofner/kubernetesdeploymentdemo:start
        ports:
        - containerPort: 80
        readinessProbe:         # remove this section if you use a different image
          httpGet:
            path: /api/Values
            port: 80
          initialDelaySeconds: 2       
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemo-service
spec:
  type: LoadBalancer
  selector:
    app: kubernetesdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80