apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azurearcdemo
  namespace: azurearcdemo
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: azurearcdemo
  chart: 
    spec:
      chart: ./AzureArcDemo/charts/azurearcdemo     