apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: workload-identity # $ServiceAccountNamespace
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa # $ServiceAccountName
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: https://kubernetesdemowolfgang.vault.azure.net/ # $KeyVaultUrl
      - name: SECRET_NAME
        value: WorkloadSecret # $KeyVaultSecret
  nodeSelector:
    kubernetes.io/os: linux