apiVersion: v1
kind: Pod
metadata:
  name: affinity-container
spec:
  containers:
  - name: affinity-container
    image: nginx
  affinity:
    nodeAffinity: 
      # preferredDuringSchedulingIgnoredDuringExecution: soft affinity
      # - weight: 1 - higher weight has more priority 1 - 100
      requiredDuringSchedulingIgnoredDuringExecution: # hard affinity
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu
            operator: In
            values:
            - nvidia
    podAntiAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx
        topologyKey: "kubernetes.io/hostname"