apiVersion: v1
kind: Pod
metadata:
  name: private-registry
spec:
  containers:
  - name: private-registry-container
    image: kubernetestrainingwolfgang.azurecr.io/nginx
    imagePullPolicy: Always
  imagePullSecrets:
  - name: registrytoken