apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: 5dd03906-2669-4d67-9c07-f37203416c17   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kubernetesdemowolfgang        # Set to the name of your key vault
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: MySecret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 6954bb4d-a0f5-4084-b434-5d10af03058e   # The tenant ID of the key vault